// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: art.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createArt = `-- name: CreateArt :one
INSERT INTO art (id, name, description, image, tags, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, image, tags, status, user_id, created_at, updated_at
`

type CreateArtParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Image       string
	Tags        []string
	UserID      uuid.UUID
}

func (q *Queries) CreateArt(ctx context.Context, arg CreateArtParams) (Art, error) {
	row := q.db.QueryRowContext(ctx, createArt,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Image,
		pq.Array(arg.Tags),
		arg.UserID,
	)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		pq.Array(&i.Tags),
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArt = `-- name: DeleteArt :one
DELETE FROM art
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteArtParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteArt(ctx context.Context, arg DeleteArtParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteArt, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getArtByID = `-- name: GetArtByID :one
SELECT id, name, description, image, tags, status, user_id, created_at, updated_at
FROM art
WHERE id = $1
`

func (q *Queries) GetArtByID(ctx context.Context, id uuid.UUID) (Art, error) {
	row := q.db.QueryRowContext(ctx, getArtByID, id)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		pq.Array(&i.Tags),
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtByUser = `-- name: GetArtByUser :many
SELECT id, name, description, image, tags, status, user_id, created_at, updated_at FROM art
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetArtByUser(ctx context.Context, userID uuid.UUID) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, getArtByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			pq.Array(&i.Tags),
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArt = `-- name: ListArt :many
SELECT id, name, description, image, tags, status, user_id, created_at, updated_at FROM art
WHERE status = 'approved'
ORDER BY created_at DESC
`

func (q *Queries) ListArt(ctx context.Context) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, listArt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			pq.Array(&i.Tags),
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtByTag = `-- name: ListArtByTag :many
SELECT id, name, description, image, tags, status, user_id, created_at, updated_at FROM art
WHERE status = 'approved'
  AND $1 = ANY(tags)
ORDER BY created_at DESC
`

func (q *Queries) ListArtByTag(ctx context.Context, tags []string) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, listArtByTag, pq.Array(tags))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			pq.Array(&i.Tags),
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtByTags = `-- name: ListArtByTags :many
SELECT id, name, description, image, tags, status, user_id, created_at, updated_at FROM art
WHERE status = 'approved'
  AND tags && $1::text[]
ORDER BY created_at DESC
`

func (q *Queries) ListArtByTags(ctx context.Context, dollar_1 []string) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, listArtByTags, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			pq.Array(&i.Tags),
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingArt = `-- name: ListPendingArt :many
SELECT id, name, description, image, tags, status, user_id, created_at, updated_at FROM art
WHERE status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingArt(ctx context.Context) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, listPendingArt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			pq.Array(&i.Tags),
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArt = `-- name: UpdateArt :one
UPDATE art
SET
    name        = COALESCE($2, name),
    description = COALESCE($3, description),
    tags        = COALESCE($4, tags),
    updated_at  = NOW()
WHERE id = $1 AND user_id = $5
RETURNING id, name, description, image, tags, status, user_id, created_at, updated_at
`

type UpdateArtParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Tags        []string
	UserID      uuid.UUID
}

func (q *Queries) UpdateArt(ctx context.Context, arg UpdateArtParams) (Art, error) {
	row := q.db.QueryRowContext(ctx, updateArt,
		arg.ID,
		arg.Name,
		arg.Description,
		pq.Array(arg.Tags),
		arg.UserID,
	)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		pq.Array(&i.Tags),
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtStatus = `-- name: UpdateArtStatus :one
UPDATE art
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, image, tags, status, user_id, created_at, updated_at
`

type UpdateArtStatusParams struct {
	ID     uuid.UUID
	Status ArtStatus
}

func (q *Queries) UpdateArtStatus(ctx context.Context, arg UpdateArtStatusParams) (Art, error) {
	row := q.db.QueryRowContext(ctx, updateArtStatus, arg.ID, arg.Status)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		pq.Array(&i.Tags),
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
