// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_Attendees.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countEventAttendees = `-- name: CountEventAttendees :one
SELECT COUNT(*)::int
FROM event_attendees
WHERE event_id = $1
`

func (q *Queries) CountEventAttendees(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countEventAttendees, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const enrollUserToEvent = `-- name: EnrollUserToEvent :one
INSERT INTO event_attendees (
    id, event_id, user_id
)
VALUES (
    $1, $2, $3
)
RETURNING id, event_id, user_id, joined_at
`

type EnrollUserToEventParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) EnrollUserToEvent(ctx context.Context, arg EnrollUserToEventParams) (EventAttendee, error) {
	row := q.db.QueryRowContext(ctx, enrollUserToEvent, arg.ID, arg.EventID, arg.UserID)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.JoinedAt,
	)
	return i, err
}

const listEventAttendees = `-- name: ListEventAttendees :many
SELECT u.id, u.name, u.password, u.email, u.description, u.banner_image, u.image, u.batch, u.social_links, u.status, u.role, u.created_at, u.updated_at
FROM users u
JOIN event_attendees ea ON ea.user_id = u.id
WHERE ea.event_id = $1
ORDER BY ea.joined_at ASC
`

func (q *Queries) ListEventAttendees(ctx context.Context, eventID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listEventAttendees, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Password,
			&i.Email,
			&i.Description,
			&i.BannerImage,
			&i.Image,
			&i.Batch,
			&i.SocialLinks,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEvents = `-- name: ListMyEvents :many
SELECT e.id, e.name, e.description, e.venue, e.image, e.banner_image, e.event_date, e.status, e.created_at, e.updated_at
FROM events e
JOIN event_attendees ea ON ea.event_id = e.id
WHERE ea.user_id = $1
ORDER BY e.event_date ASC
`

func (q *Queries) ListMyEvents(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listMyEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.BannerImage,
			&i.EventDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromEvent = `-- name: RemoveUserFromEvent :one
DELETE FROM event_attendees
WHERE event_id = $1 AND user_id = $2
RETURNING event_id
`

type RemoveUserFromEventParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveUserFromEvent(ctx context.Context, arg RemoveUserFromEventParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, removeUserFromEvent, arg.EventID, arg.UserID)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}
