// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id, name, description, venue, image, banner_image, event_date, status
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, description, venue, image, banner_image, event_date, status, created_at, updated_at
`

type CreateEventParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Venue,
		arg.Image,
		arg.BannerImage,
		arg.EventDate,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Venue,
		&i.Image,
		&i.BannerImage,
		&i.EventDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :one
DELETE FROM events
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteEvent, id)
	err := row.Scan(&id)
	return id, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, name, description, venue, image, banner_image, event_date, status, created_at, updated_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Venue,
		&i.Image,
		&i.BannerImage,
		&i.EventDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, description, venue, image, banner_image, event_date, status, created_at, updated_at
FROM events
ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.BannerImage,
			&i.EventDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByMode = `-- name: ListEventsByMode :many
SELECT id, name, description, venue, image, banner_image, event_date, status, created_at, updated_at
FROM events
WHERE status = $1
ORDER BY event_date ASC
`

func (q *Queries) ListEventsByMode(ctx context.Context, status ModeOfConduct) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByMode, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.BannerImage,
			&i.EventDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, name, description, venue, image, banner_image, event_date, status, created_at, updated_at
FROM events
WHERE event_date >= CURRENT_DATE
ORDER BY event_date ASC
`

func (q *Queries) ListUpcomingEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Venue,
			&i.Image,
			&i.BannerImage,
			&i.EventDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    name = $2,
    description = $3,
    venue = $4,
    image = $5,
    banner_image = $6,
    event_date = $7,
    status = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, venue, image, banner_image, event_date, status, created_at, updated_at
`

type UpdateEventParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Venue       sql.NullString
	Image       sql.NullString
	BannerImage sql.NullString
	EventDate   time.Time
	Status      ModeOfConduct
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Venue,
		arg.Image,
		arg.BannerImage,
		arg.EventDate,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Venue,
		&i.Image,
		&i.BannerImage,
		&i.EventDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
