// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    COALESCE($10::jsonb, '{}'::jsonb)
)
RETURNING 
    id,
    name,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Name        string
	Email       string
	Password    string
	Batch       string
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	Column10    json.RawMessage
}

type CreateUserRow struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Batch       string
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Batch,
		arg.Status,
		arg.Role,
		arg.Image,
		arg.BannerImage,
		arg.Description,
		arg.Column10,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT 
    id,
    name,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Batch       string
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    name,
    email,
    password,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links,
    created_at,
    updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Password    string
	Batch       string
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchUserAdmin = `-- name: PatchUserAdmin :one
UPDATE users
SET
    status = COALESCE($2, status),
    role = COALESCE($3, role),
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    name,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links,
    created_at,
    updated_at
`

type PatchUserAdminParams struct {
	ID     uuid.UUID
	Status AccountStatus
	Role   UserRole
}

type PatchUserAdminRow struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Batch       string
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) PatchUserAdmin(ctx context.Context, arg PatchUserAdminParams) (PatchUserAdminRow, error) {
	row := q.db.QueryRowContext(ctx, patchUserAdmin, arg.ID, arg.Status, arg.Role)
	var i PatchUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchUserImages = `-- name: PatchUserImages :one
UPDATE users
SET
    image = COALESCE($2, image),
    banner_image = COALESCE($3, banner_image),
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    image,
    banner_image,
    description,
    social_links,
    updated_at
`

type PatchUserImagesParams struct {
	ID          uuid.UUID
	Image       sql.NullString
	BannerImage sql.NullString
}

type PatchUserImagesRow struct {
	ID          uuid.UUID
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
	UpdatedAt   time.Time
}

func (q *Queries) PatchUserImages(ctx context.Context, arg PatchUserImagesParams) (PatchUserImagesRow, error) {
	row := q.db.QueryRowContext(ctx, patchUserImages, arg.ID, arg.Image, arg.BannerImage)
	var i PatchUserImagesRow
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
		&i.UpdatedAt,
	)
	return i, err
}

const patchUserPassword = `-- name: PatchUserPassword :one
UPDATE users
SET
    password = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    updated_at
`

type PatchUserPasswordParams struct {
	ID       uuid.UUID
	Password string
}

type PatchUserPasswordRow struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) PatchUserPassword(ctx context.Context, arg PatchUserPasswordParams) (PatchUserPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, patchUserPassword, arg.ID, arg.Password)
	var i PatchUserPasswordRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const patchUserProfile = `-- name: PatchUserProfile :one
UPDATE users
SET
    name = COALESCE($1::text, name),
    email = COALESCE($2::text, email),
    batch = COALESCE($3::text, batch),
    description = COALESCE($4::text, description),
    social_links = COALESCE($5::jsonb, social_links),
    updated_at = NOW()
WHERE id = $6
RETURNING
    id,
    name,
    email,
    batch,
    status,
    role,
    image,
    banner_image,
    description,
    social_links,
    created_at,
    updated_at
`

type PatchUserProfileParams struct {
	Name        sql.NullString
	Email       sql.NullString
	Batch       sql.NullString
	Description sql.NullString
	SocialLinks pqtype.NullRawMessage
	ID          uuid.UUID
}

type PatchUserProfileRow struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Batch       string
	Status      AccountStatus
	Role        UserRole
	Image       sql.NullString
	BannerImage sql.NullString
	Description sql.NullString
	SocialLinks json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) PatchUserProfile(ctx context.Context, arg PatchUserProfileParams) (PatchUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, patchUserProfile,
		arg.Name,
		arg.Email,
		arg.Batch,
		arg.Description,
		arg.SocialLinks,
		arg.ID,
	)
	var i PatchUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.Image,
		&i.BannerImage,
		&i.Description,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
